#!/bin/bash
# Complete rotation check with project metadata verification

echo ""
echo "========================================================"
echo "Annotation Rotation + Project Metadata Check"
echo "========================================================"

# Get rotation
rotation=$(ssh root@159.65.158.26 "docker exec orbit_db psql -U sitara -d sitara_crm -t -c \"SELECT jsonb_path_query(vector_metadata, '$.annos[*] ? (@.id == 1776313640186)')->>'rotation' FROM vector_projects WHERE id = 'e5d4d219-57cd-4b85-8b84-d55c661cfa98';\"" | tr -d ' ')

# Get project metadata including updated_at
metadata=$(ssh root@159.65.158.26 "docker exec orbit_db psql -U sitara -d sitara_crm -t -c \"SELECT id, vector_metadata->>'mapType' as map_type, COALESCE(vector_metadata->>'isAutoGenerated', 'false') as is_auto, updated_at FROM vector_projects WHERE id = 'e5d4d219-57cd-4b85-8b84-d55c661cfa98';\"")

echo "Project ID: e5d4d219-57cd-4b85-8b84-d55c661cfa98"
echo "ID Suffix:  ...d55c661cfa98"
echo ""
echo "$metadata" | while read line; do
    if [[ ! -z "$line" ]]; then
        echo "Project metadata: $line"
    fi
done
echo ""
echo "Annotation ID:   1776313640186"
echo "Annotation Note: Ahmed Hassan"
echo "Current Rotation: ${rotation}°"
echo ""
echo "========================================================"
echo ""
