#!/usr/bin/env python3
"""
Verify annotation rotation persistence on remote Orbit API.
Usage: python verify_annotation_rotation.py <project_id> [annotation_id]
"""

import sys
import json
import subprocess

def query_project(project_id):
    """Fetch project data via SSH + curl"""
    cmd = [
        "ssh", "root@159.65.158.26",
        f"curl -s http://localhost:8001/api/vector/projects/{project_id}"
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"ERROR: {result.stderr}")
        sys.exit(1)

    try:
        data = json.loads(result.stdout)
        return data
    except json.JSONDecodeError as e:
        print(f"ERROR: Invalid JSON response: {e}")
        print(f"Response: {result.stdout}")
        sys.exit(1)

def extract_annotation_info(project_data, target_anno_id=None):
    """Extract relevant annotation info"""
    metadata = project_data.get('vector_metadata', {})
    annotations = metadata.get('annotations', [])

    print(f"\n{'='*80}")
    print(f"PROJECT: {project_data.get('name')}")
    print(f"ID: {project_data.get('id')} (suffix: ...{project_data.get('id')[-12:]})")
    print(f"Map Type: {metadata.get('mapType', 'N/A')}")
    print(f"Auto-generated: {metadata.get('isAutoGenerated', False)}")
    print(f"Total Annotations: {len(annotations)}")
    print(f"{'='*80}\n")

    if not annotations:
        print("⚠️  No annotations found in project metadata")
        return

    if target_anno_id:
        # Find specific annotation
        found = None
        for anno in annotations:
            if anno.get('id') == target_anno_id:
                found = anno
                break

        if found:
            print(f"🎯 Target Annotation: {target_anno_id}")
            print(f"   Text: {found.get('text', 'N/A')}")
            print(f"   Rotation: {found.get('rotation', 0)}°")
            print(f"   Position: ({found.get('x', 0)}, {found.get('y', 0)})")
            print(f"   Font Size: {found.get('fontSize', 14)}")
        else:
            print(f"⚠️  Annotation {target_anno_id} NOT FOUND")
    else:
        # Show all annotations with rotation
        print("All Annotations:")
        for i, anno in enumerate(annotations, 1):
            rotation = anno.get('rotation', 0)
            marker = "🔄" if rotation != 0 else "  "
            print(f"{marker} {i}. ID: {anno.get('id')}")
            print(f"      Text: {anno.get('text', 'N/A')}")
            print(f"      Rotation: {rotation}°")
            print(f"      Position: ({anno.get('x', 0)}, {anno.get('y', 0)})")
            print()

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python verify_annotation_rotation.py <project_id> [annotation_id]")
        sys.exit(1)

    project_id = sys.argv[1]
    annotation_id = sys.argv[2] if len(sys.argv) > 2 else None

    project_data = query_project(project_id)
    extract_annotation_info(project_data, annotation_id)
